/**
 * @file gen-compression-vectors.c
 * @brief APX-176 vector generator: emits the checked-in cross-engine
 * compatibility frames for the v2 compression codecs.
 *
 * This tool is the provenance for the frozen byte arrays in the APX-176 test
 * section of core/compression.c. Each frame is produced by the reference
 * implementation the main-branch C++ engine calls, NOT by the v2 codec glue:
 *
 *   - zstd: main's Compression.cpp `case CompressionMode::ZSTD`:
 *           ZSTD_compress(dst, dstCap, src, srcSize, CompressionDefaultLevel = 3)
 *   - lz4:  main's commented-out LZ4 branch:
 *           LZ4_compress_default(src, dst, srcSize, dstCap), preceded by the
 *           v2 little-endian u64 original-size header (the v2 framing).
 *   - zlib: miniz's canonical zlib-compatible one-shot API
 *           mz_compress2(dst, &dstSize, src, srcSize, 6) -- a standard RFC 1950
 *           zlib stream with the same level/window/strategy defaults the v2
 *           codec uses -- preceded by the same v2 size header. Byte-identical
 *           to v2's tdefl path on these corpora and decodable by any zlib
 *           (cross-checked against Python's zlib.compress, level 6).
 *
 * Build + run from the repo root:
 *   ./scripts/gen-compression-vectors.sh
 * It prints a complete, self-contained C block (corpus + frame arrays) for
 * core/compression.c; paste it into the APX-176 test section. The v2 codecs
 * must decompress every frame byte-for-byte AND re-emit it byte-for-byte at
 * their default level, so the suite fails loudly if a codec's wire format
 * drifts from these frozen bytes.
 */

#include <stdio.h>
#include <string.h>
#include <stdint.h>

typedef uint8_t u8;
typedef uint32_t u32;
typedef uint64_t u64;
typedef const char* const_chr_t;

#include "zstd.h"
#include "lz4.h"
#include "miniz.h"

#define COMPRESSION_SIZE_PREFIX_BYTES 8u

#define COMPAT_LINE_TEXT "Skore v2 cross-engine compatibility vector corpus: ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 0123456789.\n"

static const u8 one_byte_data[] = {0x41u};
static const u8 fixture_data[] = "Skore v2 compression main-branch compatibility fixture\n";
static u8 compressible_data[768];
static u8 incompressible_data[768];

typedef struct vector_t {
	const_chr_t name;
	const u8* payload;
	u64 payload_size;
} vector_t;

static void write_u64_le(u8* dest, u64 value) {
	dest[0] = (u8)(value);
	dest[1] = (u8)(value >> 8u);
	dest[2] = (u8)(value >> 16u);
	dest[3] = (u8)(value >> 24u);
	dest[4] = (u8)(value >> 32u);
	dest[5] = (u8)(value >> 40u);
	dest[6] = (u8)(value >> 48u);
	dest[7] = (u8)(value >> 56u);
}

static void emit_frame_array(const_chr_t codec, const vector_t* vector, const u8* frame, u64 frame_size) {
	printf("/* %s: %llu payload bytes -> %llu frame bytes */\n", vector->name, (unsigned long long)vector->payload_size, (unsigned long long)frame_size);
	printf("static const u8 compat_%s_%s_frame[] = {\n", codec, vector->name);
	for (u64 i = 0u; i < frame_size; ++i) {
		printf("%s0x%02X,%s", (i % 12u == 0u) ? "\t" : " ", frame[i], ((i + 1u) % 12u == 0u || i + 1u == frame_size) ? "\n" : " ");
	}
	printf("};\n\n");
}

int main(void) {
	static const u8 empty_data[1] = {0u};
	u8 zstd_frame[8192];
	u8 lz4_frame[8192];
	u8 zlib_frame[8192];
	vector_t vectors[5];
	const size_t corpus_count = sizeof(vectors) / sizeof(vectors[0]);
	size_t i;

	/* Deterministic corpora -- constructed identically in the test section. */
	for (i = 0u; i < sizeof(compressible_data); ++i) {
		compressible_data[i] = (u8)COMPAT_LINE_TEXT[i % (sizeof(COMPAT_LINE_TEXT) - 1u)];
	}
	{
		u32 state = 0x6D2B79F5u;
		for (i = 0u; i < sizeof(incompressible_data); ++i) {
			state ^= state << 13u;
			state ^= state >> 17u;
			state ^= state << 5u;
			incompressible_data[i] = (u8)(state >> 24u);
		}
	}

	vectors[0].name = "empty";
	vectors[0].payload = empty_data;
	vectors[0].payload_size = 0u;
	vectors[1].name = "one_byte";
	vectors[1].payload = one_byte_data;
	vectors[1].payload_size = sizeof(one_byte_data);
	vectors[2].name = "fixture";
	vectors[2].payload = fixture_data;
	vectors[2].payload_size = sizeof(fixture_data) - 1u;
	vectors[3].name = "compressible";
	vectors[3].payload = compressible_data;
	vectors[3].payload_size = sizeof(compressible_data);
	vectors[4].name = "incompressible";
	vectors[4].payload = incompressible_data;
	vectors[4].payload_size = sizeof(incompressible_data);

	printf("/*\n * APX-176 cross-engine compatibility vectors (frozen).\n"
		   " * Generated by scripts/gen-compression-vectors.c -- do not hand-edit.\n"
		   " * Regenerate with scripts/gen-compression-vectors.sh and re-verify the\n"
		   " * full suite; the frames below are the reference implementations'\n"
		   " * output (see the generator header for exact provenance).\n"
		   " */\n\n");

	printf("#ifdef SK_COMPRESSION_HAS_ZSTD\n");
	printf("/* zstd frames: main Compression.cpp `case ZSTD` -- ZSTD_compress, level 3. */\n");
	for (i = 0u; i < corpus_count; ++i) {
		const size_t src_size = (size_t)vectors[i].payload_size;
		const size_t rc = ZSTD_compress(zstd_frame, sizeof(zstd_frame), vectors[i].payload, src_size, 3);
		if (ZSTD_isError(rc)) {
			fprintf(stderr, "zstd compress failed for %s: %s\n", vectors[i].name, ZSTD_getErrorName(rc));
			return 1;
		}
		emit_frame_array("zstd", &vectors[i], zstd_frame, rc);
	}
	printf("#endif /* SK_COMPRESSION_HAS_ZSTD */\n\n");

	printf("#ifdef SK_COMPRESSION_HAS_LZ4\n");
	printf("/* lz4 frames: main's commented-out LZ4 branch -- LZ4_compress_default + size prefix. */\n");
	for (i = 0u; i < corpus_count; ++i) {
		const size_t src_size = (size_t)vectors[i].payload_size;
		const int rc = LZ4_compress_default((const char*)vectors[i].payload, (char*)(lz4_frame + COMPRESSION_SIZE_PREFIX_BYTES), (int)src_size,
											(int)(sizeof(lz4_frame) - COMPRESSION_SIZE_PREFIX_BYTES));
		if (rc <= 0) {
			fprintf(stderr, "lz4 compress failed for %s\n", vectors[i].name);
			return 1;
		}
		write_u64_le(lz4_frame, vectors[i].payload_size);
		emit_frame_array("lz4", &vectors[i], lz4_frame, COMPRESSION_SIZE_PREFIX_BYTES + (u64)rc);
	}
	printf("#endif /* SK_COMPRESSION_HAS_LZ4 */\n\n");

	printf("#ifdef SK_COMPRESSION_HAS_MINIZ\n");
	printf("/* zlib frames: mz_compress2 level 6 (RFC 1950) + size prefix. */\n");
	for (i = 0u; i < corpus_count; ++i) {
		const size_t src_size = (size_t)vectors[i].payload_size;
		mz_ulong out_size = (mz_ulong)(sizeof(zlib_frame) - COMPRESSION_SIZE_PREFIX_BYTES);
		const int rc = mz_compress2((mz_uint8*)(zlib_frame + COMPRESSION_SIZE_PREFIX_BYTES), &out_size, (const mz_uint8*)vectors[i].payload, (mz_ulong)src_size, 6);
		if (rc != MZ_OK) {
			fprintf(stderr, "zlib compress failed for %s: %d\n", vectors[i].name, rc);
			return 1;
		}
		write_u64_le(zlib_frame, vectors[i].payload_size);
		emit_frame_array("zlib", &vectors[i], zlib_frame, COMPRESSION_SIZE_PREFIX_BYTES + (u64)out_size);
	}
	printf("#endif /* SK_COMPRESSION_HAS_MINIZ */\n");

	return 0;
}
