#!/usr/bin/env python3
"""Regenerate editor/content/skore_editor_icons_embed.h from the bitmap icons
in editor/content/images/ (the C++ editor's Content/Images set, copied from
origin/main 62b1d00e). The header embeds the raw PNG/JPEG bytes so the v2
editor can decode + atlas them at runtime without a filesystem dependency
(same pattern as plugins/ui/testdata/skore_test_font_ttf.h).

Usage:
    python3 scripts/gen-editor-icons-embed.py [--out editor/content/skore_editor_icons_embed.h]
"""

import argparse
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES_DIR = os.path.join(REPO_ROOT, "editor", "content", "images")
DEFAULT_OUT = os.path.join(REPO_ROOT, "editor", "content", "skore_editor_icons_embed.h")

# (array name, source file under editor/content/images/, C++ Content/Images path)
ICONS = [
    ("sk_editor_icon_folder_png", "FolderIcon.png", "Content/Images/FolderIcon.png"),
    ("sk_editor_icon_file_png", "FileIcon.png", "Content/Images/FileIcon.png"),
    # The vendored stb_image builds with STBI_ONLY_PNG, so the JPEG logo is
    # embedded as the RGBA PNG conversion (same 128x128 pixels) committed
    # next to the original.
    ("sk_editor_icon_logo_small_png", "logo_small.png", "Content/Images/LogoSmall.jpeg -> logo_small.png"),
    ("sk_editor_icon_logo_minimal_png", "minimalist-logo.png", "Content/Images/minimalist-logo.png"),
    # skore.ico is a Win32 ICO; stb_image cannot decode ICO, so the loader uses
    # the RGBA PNG conversion (same 128x128 pixels) committed next to it.
    ("sk_editor_icon_skore_png", "skore.png", "Content/Images/skore.ico -> skore.png"),
]

HEADER = """/* Auto-generated by scripts/gen-editor-icons-embed.py; do not edit. */
/* Source bitmaps: editor/content/images/ (C++ editor Content/Images set from */
/* origin/main 62b1d00e62a97747a95b16f11a9f9c8bdc1c29a0). Decoded at runtime  */
/* with stb_image and packed into one RGBA8 atlas (APX-367).                  */
#pragma once

#include "common.h"

"""


def emit_array(f, name, data):
    f.write("static const u8 %s[%u] =\n\t{" % (name, len(data)))
    for i, b in enumerate(data):
        if i % 16 == 0:
            f.write("\n\t ")
        f.write(" 0x%02x," % b)
    f.write("\n};\n\n")


def main():
    parser = argparse.ArgumentParser(description="Regenerate the editor icon embed header")
    parser.add_argument("--out", default=DEFAULT_OUT, help="output header path")
    args = parser.parse_args()

    with open(args.out, "w") as f:
        f.write(HEADER)
        for array_name, file_name, cpp_path in ICONS:
            src = os.path.join(IMAGES_DIR, file_name)
            with open(src, "rb") as fh:
                data = fh.read()
            f.write("/* %s (%u bytes) */\n" % (cpp_path, len(data)))
            emit_array(f, array_name, data)
        # Symbolic sizes for callers that want sizeof without the array (arrays
        # are static so sizeof works in the same TU only).
        for array_name, file_name, _ in ICONS:
            src = os.path.join(IMAGES_DIR, file_name)
            size = os.path.getsize(src)
            f.write("static const u32 %s_size = %uu;\n" % (array_name, size))

    print("wrote %s (%d icons)" % (args.out, len(ICONS)))


if __name__ == "__main__":
    sys.exit(main())
